/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        if(n<2){
  return false;
}
  for(int i=2; i<= Math.sqrt(n); i++){
    if(n%i == 0){
      return false;
    }
      
  }
  return true;
    }
    public long firstPrimeNumberIn(String n) {
        // Write your code here.
        return -1;
    }
}
